apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: jenkins-ngninx
  namespace: consiti-bootcamp-1
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: jenkins-ejercicio@consiti-bootcamp-1.iam.gserviceaccount.com
      containers:
      - name: nginx-jenkinksprueba 
        image:  nginx
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 80
        

      # - name: svfe-api-firmador-1
      #   image: svfe/svfe-api-firmador:v20230109
      #   resources:
      #     limits:
      #       cpu: 1000m
      #       memory: 512Mi
      #   volumeMounts:
      #   - name: certifados
      #     mountPath: /uploads
      # volumes:
      # - name: certifados
      #   csi:
      #     driver: gcsfuse.run.googleapis.com
      #     readOnly: true
      #     volumeAttributes:
      #       bucketName: certifados_prod